name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=$(pwd) pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # runs only if tests pass
    steps:
      - uses: actions/checkout@v3
      - name: Deploy files
        run: |
          mkdir -p /tmp/test-deploy
          cp -r app/* /tmp/test-deploy/